### ISSUE TITLE
leNet not work with keras 2.3.1

### ISSUE THREAD

**Issue by luoXH2016** [PacktPublishing/Deep-Learning-with-Keras#20]
Chapter03/keras_LeNet.py
line 58: AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'
line 28: ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_1/MaxPool' (op: 'MaxPool') with input shapes: [?,
1,28,20].

**Comment by sonam-packt** [comment]
Hello @luoXH2016,
We have an updated version of this book "Advanced Deep Leaning with Keras" you can check out. Here is the link https://www.packtpub.com/in/big-data-and-business-intelligence/advanced-deep-learning-keras
Kindly check it out.

Thank you.
